roundtrip: Exit on command failure

diff --git a/misc/roundtrip b/misc/roundtrip
--- a/misc/roundtrip
+++ b/misc/roundtrip
@@ -15,6 +15,8 @@
 #   You should have received a copy of the GNU General Public License
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+set -e
+
 # Avoid trouble with weird bytes on non-C locales
 export LC_ALL=C
 
@@ -46,10 +48,12 @@ OLD_IFS="$IFS"
 IFS='
 '
 
-for tags in $(find "$UNITS" -name expected.tags); do
-    for t in $(sed -e 's/^\([^	]*\)	.*/\1/' "$tags"); do
-	if [ 1 -gt $("${READTAGS}" -t "$tags" - "$t" 2>/dev/null | wc -l) ]; then
-	    printf 'FAILED: "%s" -t "%s" - "%s"\n' "${READTAGS}" "$tags" "$t"
+tagfiles=$(find "$UNITS" -name expected.tags)
+for tags in $tagfiles; do
+    tagnames=$(sed -e 's/^\([^	]*\)	.*/\1/' "$tags")
+    for name in $tagnames; do
+	if [ 1 -gt $("${READTAGS}" -t "$tags" - "$name" 2>/dev/null | wc -l) ]; then
+	    printf 'FAILED: "%s" -t "%s" - "%s"\n' "${READTAGS}" "$tags" "$name"
 	    s=1
 	fi
     done
